export default {
  skills: 'Skills',
  webDev: 'Web Development',
  programmingLanguages: 'Languages',
  frameworks: 'Libraries & Frameworks',
  other: 'Other',
  languages: 'Languages',
  programming: 'Programming',
  certificates: 'Certificates',
  experience: 'Experience',
  education: 'Education',
  projects: 'Projects',
  position: 'Position',
  description: 'Description',
  technologies: 'Technologies',
  course: 'Course',
  advancedClasses: 'Advanced Classes',
  average: 'Average',
  diploma: 'Diploma',
  from: 'From',
  to: 'To',
}
