export default {
  skills: `Umiejętności`,
  webDev: 'Web Development',
  programmingLanguages: `Języki`,
  frameworks: `Biblioteki i Frameworki`,
  other: 'Inne',
  languages: `Języki`,
  programming: `Programowanie`,
  certificates: `Certyfikaty`,
  experience: `Doświadczenie`,
  education: `Edukacja`,
  projects: `Projekty`,
  position: `Stanowisko`,
  description: `Opis`,
  technologies: `Technologie`,
  course: `Kurs`,
  advancedClasses: `Na poziomie zaawansowanym`,
  average: 'Średnia',
  diploma: 'Dyplom',
  from: 'Od',
  to: 'Do',
}
